import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        primary: {
          light: "var(--color-primary-light)",
          "light-hover": "var(--color-primary-light-hover)",
          "light-active": "var(--color-primary-light-active)",
          DEFAULT: "var(--color-primary-normal)",
          hover: "var(--color-primary-normal-hover)",
          active: "var(--color-primary-normal-active)",
          dark: "var(--color-primary-dark)",
          "dark-hover": "var(--color-primary-dark-hover)",
          "dark-active": "var(--color-primary-dark-active)",
          darker: "var(--color-primary-darker)",
        },
        secondary: {
          light: "var(--color-secondary-light)",
          "light-hover": "var(--color-secondary-light-hover)",
          "light-active": "var(--color-secondary-light-active)",
          DEFAULT: "var(--color-secondary-normal)",
          hover: "var(--color-secondary-normal-hover)",
          active: "var(--color-secondary-normal-active)",
          dark: "var(--color-secondary-dark)",
          "dark-hover": "var(--color-secondary-dark-hover)",
          "dark-active": "var(--color-secondary-dark-active)",
          darker: "var(--color-secondary-darker)",
        },
        tertiary: {
          light: "var(--color-tertiary-light)",
          "light-hover": "var(--color-tertiary-light-hover)",
          "light-active": "var(--color-tertiary-light-active)",
          DEFAULT: "var(--color-tertiary-normal)",
          hover: "var(--color-tertiary-normal-hover)",
          active: "var(--color-tertiary-normal-active)",
          dark: "var(--color-tertiary-dark)",
          "dark-hover": "var(--color-tertiary-dark-hover)",
          "dark-active": "var(--color-tertiary-dark-active)",
          darker: "var(--color-tertiary-darker)",
        },
        background: {
          DEFAULT: "var(--color-bg-normal)",
          light: "var(--color-bg-light)",
          dark: "var(--color-bg-dark)",
        },
        txt: {
          primary: "var(--text-primary-normal)",
          secondary: "var(--text-secondary-normal)",
        },
        alert: {
          DEFAULT: "var(--color-alert)",
          hover: "var(--color-alert-hover)",
          pressed: "var(--color-alert-pressed)",
        },
        success: {
          DEFAULT: "var(--color-success)",
          hover: "var(--color-success-hover)",
          pressed: "var(--color-success-pressed)",
        },
        warning: {
          1: "var(--color-warning-1)",
          "1-hover": "var(--color-warning-1-hover)",
          "1-pressed": "var(--color-warning-1-pressed)",
          2: "var(--color-warning-2)",
          "2-hover": "var(--color-warning-2-hover)",
          "2-pressed": "var(--color-warning-2-pressed)",
        },
        info: {
          DEFAULT: "var(--color-info)",
          hover: "var(--color-info-hover)",
          pressed: "var(--color-info-pressed)",
        },
        disabled: {
          DEFAULT: "var(--color-disabled)",
          hover: "var(--color-disabled-hover)",
          pressed: "var(--color-disabled-pressed)",
        },
        "text-btn": {
          1: "var(--color-text-btn-01)",
          2: "var(--color-text-btn-02)",
          3: "var(--color-text-btn-03)",
        }
      },
      fontFamily: {
        sans: ["var(--font-family-primary)"],
      },
      fontWeight: {
        light: "var(--font-weight-light)",
        regular: "var(--font-weight-regular)",
        medium: "var(--font-weight-medium)",
        semibold: "var(--font-weight-semibold)",
        bold: "var(--font-weight-bold)",
        extrabold: "var(--font-weight-extrabold)",
      },
      fontSize: {
        h1: "var(--text-h1)",
        h2: "var(--text-h2)",
        h3: "var(--text-h3)",
        h4: "var(--text-h4)",
        h5: "var(--text-h5)",
        h6: "var(--text-h6)",
        p1: "var(--text-p1)",
        p2: "var(--text-p2)",
        p3: "var(--text-p3)",
        p4: "var(--text-p4)",
        p5: "var(--text-p5)",
        p6: "var(--text-p6)",
      },
      spacing: {
        "ds-01": "var(--spacing-01)",
        "ds-02": "var(--spacing-02)",
        "ds-03": "var(--spacing-03)",
        "ds-04": "var(--spacing-04)",
        "ds-05": "var(--spacing-05)",
        "ds-06": "var(--spacing-06)",
        "ds-07": "var(--spacing-07)",
        "ds-08": "var(--spacing-08)",
        "ds-09": "var(--spacing-09)",
        "ds-10": "var(--spacing-10)",
        "ds-11": "var(--spacing-11)",
        "grid-margin": "var(--grid-margin)",
        "grid-gutter": "var(--grid-gutter)",
      },
      borderRadius: {
        "ds-01": "var(--round-01)",
        "ds-02": "var(--round-02)",
        "ds-03": "var(--round-03)",
        "ds-04": "var(--round-04)",
        "ds-05": "var(--round-05)",
        "ds-06": "var(--round-06)",
        "ds-07": "var(--round-07)",
        "ds-08": "var(--round-08)",
        "ds-09": "var(--round-09)",
      },
      borderWidth: {
        "ds-01": "var(--stroke-01)",
        "ds-02": "var(--stroke-02)",
        "ds-03": "var(--stroke-03)",
        "ds-04": "var(--stroke-04)",
        "ds-05": "var(--stroke-05)",
        "ds-06": "var(--stroke-06)",
      },
      gridTemplateColumns: {
        'design': 'repeat(var(--grid-columns), minmax(0, 1fr))',
      },
    },
  },
  plugins: [],
};

export default config;